server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: ms-productos

  sql:
    init:
      mode: never

  r2dbc:
    url: r2dbc:postgresql://${DB_HOST:ep-lingering-dust-ahp11our-pooler.c-3.us-east-1.aws.neon.tech}:${DB_PORT:5432}/${DB_NAME:neondb}?sslMode=${DB_SSL_MODE:require}
    username: ${DB_USER:neondb_owner}
    password: ${DB_PASSWORD:npg_dtSPD6gb9aks}
